### ISSUE TITLE
Option to only check level 30-40 accounts

### ISSUE THREAD

**Issue by tokar86a** [sLoPPydrive/PGNumbra#11]
Could you add a option so it is possible for the PGNumber to only check account between level 30 and 40 that you have add in the PGPool?  

When you use the --highlvl-workers in Rocket Map the account dont get the shadowbanning flag.

**Comment by tomballgithub** [comment]
I will write a PR for this

**Comment by boby360** [comment]
Could it just be a defined level range. aka if you had level 1s that were imported via pgpool. Iv also found myself sitting on a ton of level 19-20 accounts that are all banned (i assume gain-exp doesn't regulate itself.) So again having the ability to define the range would be awesome.

**Comment by tomballgithub** [comment]
Yes I plan to do min_level and max_level for PGNumbra which PGPool already
does support.

**Comment by boby361** [comment]
Awesome. Very much appreciated.

**Comment by sLoPPydrive** [comment]
Thanks @tomballgithub for posting the PR which has been merged. :)
