### ISSUE TITLE
Some bug to level up more then level 2

### ISSUE THREAD

**Issue by m3g4mInD** [sLoPPydrive/PGNumbra#12]
I know this  script is to reach lv2  and i love this new feature.
In cfg:  
spin-below-level: 20
max-spins: 1000

Almost accounts reach level 2 and one reach level 12 , same place, new accounts.

![screenshot_5](https://user-images.githubusercontent.com/9365134/31633139-ba41b066-b2bf-11e7-9f0b-b137c46f666c.png)

**Comment by bbdoc** [comment]
The lvl 12 account was not a new one... it can't be that it encountered 176 pokemons or walked 9.9km only by PGNumbra... those are stuff PGNumbra is not doing...

**Comment by m3g4mInD** [comment]
@bbdoc  yes are new accts, i have restart 3 times the script after he finnish, that is why they reach lv2 and the account lv12 was new like the others, i have made 1hr ago rofl and they just login on pgnumbra loool

**Comment by sLoPPydrive** [comment]
It is highly unlikely that this was a completely new account. PGNumbra only spins Pokestops in range (in your case up to 1000 stops - I think there is no place on earth where you can reach 1000 Pokestops 😂) and doesn't walk or catch any Pokemon. But nevertheless.... what is the bug?

If you think the account cannot be Level 12 then please log in using the real app to confirm. ;-)

**Comment by m3g4mInD** [comment]
@sLoPPydrive you are correct #close
