### ISSUE TITLE
hashing quote exceeded with 1 thread?

### ISSUE THREAD

**Issue by Ben-13** [sLoPPydrive/PGNumbra#17]
Unsure if there is a way to slow things down though it doesn't seem to run "too fast" but after checking about 10 accounts I start getting hashing limit exceeded and it stops checking accounts.  I've even tried using a new (small) key just to check.  

Error is:
Thread-1][   pogoaccount][ WARNING] [wczhb3mk2s5r] HashingQuotaExceededException('429: Request limited, error: Your request has been limited.',): Retrying in 5.0s.

Thing is I can use the same key with RM a few seconds later without issue so I don't think its bossland throttling me, and even if so with 1 thread it seems unlikely on a 500 rpm hash.

**Comment by sLoPPydrive** [comment]
The full account login procedure takes about 30-40 requests, so yes, a bossland throttle is totally possible.

As PGNumbra is using MrMime as API abstraction you can modify the login behavior by creating the file `mrmime_config.json` and entering the following:
```
{
  "download_assets_and_items": false
}
```
This will skip the biggest part of the login requests which aren't technically necessary on every login. You can go even one step further and completely remove the login sequence with `"full_login_flow": false` in the same file.

**Comment by Ben-13** [comment]
As a thought, is there a way to set a delay between logins to help mitigate this? I don't mind if it takes longer but if we could set a 10-30 second delay between trying accounts it might prevent the issue.
