### ISSUE TITLE
checkonce_threads cfg not working, always using 10 threads

### ISSUE THREAD

**Issue by dsorc** [sLoPPydrive/PGNumbra#2]
In config.json set
  "checkonce_threads": 2

10 accounts are logged in, and are tested at the same time. (expected 2 at a time)

Also, there is no login delay between successful logins. (it should be a cfg parameter, but this is another issue)

**Comment by sLoPPydrive** [comment]
Please do a `git pull` and check the README. It's all documented. The parameter is now `shadowcheck_threads` and you can define a `login_delay`.

In fact there is no such thing as a delay between checking 2 different accounts. Might add that in the future. ;)
