### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by jorgitoh** [sLoPPydrive/PGNumbra#3]
Something is wrong with the new code. Im using 2 versions of this. One of them from 5 days ago. All my accounts works fine but with the new version ( same .json ) all my accounts are shadowbanned.

**Comment by sLoPPydrive** [comment]
I added Ponyta to the list of common Pokemon which can be seen by all accounts. Could this be it? Do you have any known good accounts? Could load up a few (suspected) bad ones and at least one good one into your accounts file and launch `compare_scans.py`? Oh and don't forget to set `include_nearby: true` in your config! This will show you exactly what they can see. You should see a difference between good and bad accounts.

Also (you might know already) the location is very important. You have to use a location where "rare" Pokemon are nearby.

**Comment by jorgitoh** [comment]
Ill check tomorow again :D
