### ISSUE TITLE
Getting error too many open files

### ISSUE THREAD

**Issue by elincognito** [sLoPPydrive/PGNumbra#4]
Having the following error

> Traceback (most recent call last):
>   File "shadowcheck.py", line 212, in <module>
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
> IOError: [Errno 24] Too many open files: 'accounts-info.txt'

Using arround 20, 25 threads. This happens when the number of accs to check is rather large > 1K
Something is not being "cleaned"
I have used `ulimit -n XXXX` as a workaround

**Comment by sLoPPydrive** [comment]
I did not synchronize file access. Fixed that. Please try again. :)

**Comment by elincognito** [comment]
Humm hot a new one :D
Don't know if related 
 Error on get_map_objects (try #2): `HashingOfflineException(ConnectionError(MaxRetryError("HTTPSConnectionPool(host='pokehash.buddyauth.com', port=443): Max retries exceeded with url: /api/v133_1/hash (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b4b457790>: Failed to establish a new connection: [Errno 24] Too many open files',))",),),)`

**Comment by sLoPPydrive** [comment]
Damn, these errors seem to come from inside the pgoapi although I still don't know what the real cause is. Might have to dig deeper...

Try using a lower number of threads.

**Comment by elincognito** [comment]
@sLoPPydrive 
`ulimit -n BIGNUMBER` seems to fix the issue however its obviously an indication that something is wrong and some files/sockets are not being proper closed

**Comment by sLoPPydrive** [comment]
Exactly. And shadowcheck.py immediately closes a file after it wrote a line to it, so there is many open/close actions (which are being synchronized since the last commit). Will have to look into debugging of such problems. Tomorrow...

**Comment by sLoPPydrive** [comment]
I found out that each PGoApi instance did not close their connection pool properly. This might not be a problem if accounts (and therefore PGoApi instances) get replaced occasionally but it was a problem when scanning through hundreds of accounts.

Fixed by properly closing connection pools.
